import os

SERVICE_HOST = os.getenv("CNN_SERVICE_HOST", "0.0.0.0")
SERVICE_PORT = int(os.getenv("CNN_SERVICE_PORT", "8000"))
CONFIDENCE_THRESHOLD = float(os.getenv("CNN_CONFIDENCE_THRESHOLD", "0.85"))
MAX_FILE_SIZE_MB = int(os.getenv("CNN_MAX_FILE_SIZE_MB", "10"))

MODEL_SAVE_PATH = os.getenv("CNN_MODEL_SAVE_PATH", "model/weights/cnn_best.pth")
IMG_SIZE = 224
NUM_CLASSES = 2
NUM_EPOCHS = 15
BATCH_SIZE = 32
LEARNING_RATE = 0.001
